### ISSUE TITLE
[Bug]: flatpak >= 1.18 FTBFS when glib < 2.72

### ISSUE THREAD

**Issue by linrs** [flatpak/flatpak#6775]
### Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [x] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [x] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.18.0 1.18.1 1.19.0

### What Linux distribution are you using?

Other (specify below)

### Linux distribution version

slackware 15.0

### What architecture are you using?

x86_64

### How to reproduce

glib < 2.72
`$ meson setup build --buildtype=release -Dsystemd=disabled -Dmalcontent=disabled -Dselinux_module=disabled -Dsystem_bubblewrap=bwrap -Dsystem_dbus_proxy=xdg-dbus-proxy -Dwerror=false`

`$ ninja -C build`

### Expected Behavior

build without errors

### Actual Behavior

[commit 17cb1135cb854f41ff8cac3757fc62daf410c44c](https://github.com/flatpak/flatpak/commit/17cb1135cb854f41ff8cac3757fc62daf410c44c) introduced new function 'g_hash_table_new_similar' which was available since glib 2.72.

https://github.com/flatpak/flatpak/blob/main/meson.build#L35 requires glib >= 2.46.

In slackware 15.0 x86_64, with gcc 11.2.0, meson 1.11.1, glib2 2.70.3,
flatpak 1.19.0 could not be built from source code.

ninja werror log: [werror.log](https://github.com/user-attachments/files/31117941/werror.log)

if I remove the werror options in meson.build
`$ sed -i '/implicit-function-declaration\|int-conversion/ s/Werror/W/' meson.build`

ninja will failed with `undefined reference to 'g_hash_table_new_similar'`:

[g_hash_table_new_similar.log](https://github.com/user-attachments/files/31117965/g_hash_table_new_similar.log)

`git revert 17cb1135cb854f41ff8cac3757fc62daf410c44c` will temporarily fix the issue.

**Comment by swick** [comment]
Yeah, that was an oversight. I suggest to apply https://github.com/flatpak/flatpak/pull/6777 instead of reverting `17cb1135cb854f41ff8cac3757fc62daf410c44c`.

**Comment by linrs** [comment]
Thanks. The issue is resolved with PR #6777.

**Comment by smcv** [comment]
#6777 hasn't been merged yet, reopening.

**Comment by razzeee** [comment]
was merged and backported, should be closeable

**Comment by smcv** [comment]
Yes, should be fixed in 1.18.2
